[package]
name = "architecture"
version = "0.1.0"
edition = "2024"

[dependencies]

chrono = "0.4"

rbs = "4.6"
rbatis = "4.6"
rbdc = "4.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
