[package]
name = "architecture"
version = "0.1.0"
edition = "2024"

[dependencies]

chrono = "0.4"

dotenvy = "0.15"

rbs = "4.6"
rbatis = "4.6"
rbdc = "4.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

axum = "0.8.6"
axum-valid = "0.24"

tokio = { version = "1.40", features = ["full"] }
tower-http = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"

uuid = { version = "1.4", features = ["v4"] }
validator = { version = "0.20", features = ["derive"] }
