[server]
env = "development"
host = "0.0.0.0"
port = 3000

[database]
host = "localhost"
port = 5432
user = "user"
pswd = "password"
database = "mydb"
schema = "public"

[logger]
level = "debug"
log_directory = "logs/"
file_prefix = "app"

[sftp]
host = "localhost"
port = 22
user = "willie"
pswd = "Cgwdy2025@2"
root = "/home/willie/"

[mail]
host = "smtp.gmail.com"
port = 587
user = "guan.yu456@gmail.com"
pswd = "ufyi kdrl orew afom"
