[server]
env = "development"
host = "0.0.0.0"
port = 3000

[database]
host = "localhost"
port = 5432
user = "user"
pswd = "password"
database = "mysql"
schema = "public"

[logger]
level = "debug"
log_directory = "logs/"
file_prefix = "app"

[secret]
jwt_secret = "your_jwt_secret_here"
refresh_secret = "your_refresh_secret_here"
